#spring.profiles.active=local
spring.profiles.active=docker

logging.pattern.level=%5p [%X{correlationId}]
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] [%thread] %logger{36} - %msg%n

# Debug
#spring.datasource.hikari.connection-test-query=SELECT 1
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.org.springframework.jdbc.datasource=DEBUG
#logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG

#logging.level.org.springframework.jdbc.core=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#logging.level.org.springframework.security=DEBUG

# actuator health endpoint
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

spring.jpa.hibernate.ddl-auto=update

# swagger properties
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs