spring.application.name=paymentsystem

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbcUrl=jdbc:mysql://mysql:3306/payment_service
spring.datasource.username=root
spring.datasource.password=

fraud.api.url=http://fraud-detection:8000/predict-fraud
fraud.api.secret.key=sk

stripe.secret.key=
stripe.init.url=https://api.stripe.com/v1/payment_intents
stripe.confirm.url=https://api.stripe.com/v1/payment_intents/{id}/confirm
