spring.application.name=paymentsystem
server.port=8181

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbcUrl=jdbc:mysql://localhost:3307/payment_service
spring.datasource.username=root
spring.datasource.password=

fraud.api.url=http://localhost:8000/predict-fraud
fraud.api.secret.key=sk

stripe.secret.key=
stripe.init.url=https://api.stripe.com/v1/payment_intents
stripe.confirm.url=https://api.stripe.com/v1/payment_intents/{id}/confirm





